⚒️ Adjust the appearance of the toolbar on mobile devices
liam-hq/liam pull request #356
Opened 2024-12-23 05:53 UTC by FunamaYukina

## Summary

## Related Issue

## Changes

## Testing

## Other Information

2024-12-23 06:24 UTC, FunamaYukina commented on frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.module.css
> +  height: calc(100svh - var(--default-header-height));
I tried using ``vh`` instead of ``svh``, but it didn't display correctly, so I went back to using ``svh``.

2024-12-23 07:29 UTC, MH4GF requested changes
The cause of the height overflow is apparently the height of the transparent marker.

<img width="792" alt="スクリーンショット 2024-12-23 16 24 20" src="https://github.com/user-attachments/assets/dd568e79-3edf-4a43-8147-24d82c7ec123" />

https://github.com/liam-hq/liam/blob/c6838375e419b845e65c5e9623e63825c28b52b0/frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/CardinalityMarkers.tsx

I'd like to adjust the cause of the overflow. Setting a fixed value for height as a last resort.

2024-12-23 08:42 UTC, FunamaYukina commented
@MH4GF 
Thanks for catching that🙏. I've removed the ``width`` and ``height`` attributes from the SVG and tested it on a real device.


![ss 2585](https://github.com/user-attachments/assets/674f198a-5e65-4aab-8357-317652c72145)

2024-12-24 03:09 UTC, MH4GF approved these changes
I don't know why it can be displayed with width and height set to 0, but it seems to work fine when called from marker.
LGTM 👍🏻

2024-12-24 03:11 UTC, merged